version: '3'
services:
  
  app:
    image: chmelovar-landing:latest
    build: .
    command: /start-reload.sh
    restart: always
    volumes:
      - ./app:/app
    ports:
      - 8080:80
    environment:
      - APP_SENDGRID_API_KEY
      - APP_MONGO_CONNECTION_STRING
      - APP_SENTRY_DSN
      - APP_SENTRY_ENVIRONMENT=dev
      - WEB_CONCURRENCY=1
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - ./data/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME
      - ME_CONFIG_MONGODB_ADMINPASSWORD
